# Generated by Django 6.0.1 on 2026-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='camera_csvs/'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlateDetection',
        ),
    ]
