# Generated by Django 6.0.1 on 2026-02-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAM', '0002_camera_csv_file_camera_last_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=50, unique=True)),
                ('video_file', models.FileField(upload_to='camera_feeds/')),
                ('last_processed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('car_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAM.camerafeed')),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
